footprint: [[-0.25, -0.20], [-0.25, 0.20], [0.25, 0.20], [0.25, -0.20]]
footprint_padding: 0.01

robot_radius: 0.3
transform_tolerance: 0.2

obstacle_layer:
  enabled: true
  obstacle_range: 5.5
  raytrace_range: 6.0
  inflation_radius: 0.2
  track_unknown_space: true
  combination_method: 1

  observation_sources: point_cloud_sensor
  point_cloud_sensor:
    sensor_frame: map
    data_type: PointCloud2
    topic: /kinect/depth/points
    marking: true
    clearing: true
    min_obstacle_height: 0.05
    max_obstacle_height: 2.0

inflation_layer:
  enabled: true
  cost_scaling_factor: 10.0
  inflation_radius: 0.5

static_layer:
  enabled: true
  map_topic: "/map"