TrajectoryPlannerROS:
  max_vel_x: 0.25
  min_vel_x: 0.1
  max_vel_theta: 0.8
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 1.5
  acc_lim_y: 1.5

  holonomic_robot: false

  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.25

  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.2

  sim_time: 2.0
  vx_samples: 15
  vtheta_samples: 30

  pdist_scale: 1.0
  gdist_scale: 0.8
  occdist_scale: 0.3

  meter_scoring: true

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  
  latch_xy_goal_tolerance: true

  min_obstacle_dist: 0.5
  heading_lookahead: 0.7

  escape_vel: -0.1

  dwa: true
  heading_scoring: true
  heading_scoring_timestep: 0.8
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
