obstacle_range: 7.0
raytrace_range: 7.5

footprint: [[-0.25, -0.30], [-0.25, 0.30], [0.25, 0.30], [0.25, -0.30]]
footprint_padding: 0.01

inflation_radius: 0.8
transform_tolerance: 0.5
update_distance_threshold: 0.1

map_type: costmap
observation_sources: laser_scan_sensor

laser_scan_sensor: {
  sensor_frame: lidar_link, 
  data_type: LaserScan, 
  topic: /scan, 
  marking: true, 
  clearing: true, 
  min_obstacle_height: 0.05, 
  max_obstacle_height: 1.0, 
  obstacle_range: 7.0,
  raytrace_range: 7.5,
  inf_is_valid: false,
  obstacle_detection_threshold: 0.7
}

inflation_layer:
  enabled: true
  cost_scaling_factor: 8.0
  inflation_radius: 0.9

obstacle_layer:
  enabled: true
  combination_method: 1
  track_unknown_space: true
  obstacle_range: 7.0
  raytrace_range: 7.5
  observation_persistence: 0.0
  min_obstacle_height: 0.05
  max_obstacle_height: 1.0
  obstacle_filters:
    - name: inflation
      type: "costmap_2d::InflationLayer"
  filter_obstacles: true