DWAPlannerROS:
  # Robot Configuration Parameters
  max_vel_x: 0.25
  min_vel_x: -0.25
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans: 0.25
  min_vel_trans: 0.1
  max_vel_theta: 1.0
  min_vel_theta: 0.3
  acc_lim_x: 1.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  min_obstacle_dist: 0.4  # Increase this value based on your new footprint

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.25
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.025
  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 40
  controller_frequency: 10.0

  # Trajectory scoring parameters
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.03
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

  # Global Plan Parameters
  publish_traj_pc: true
  publish_cost_grid_pc: true

  # Debugging
  dwa: true
  global_frame_id: odom

  # Differential-drive robot configuration
  holonomic_robot: false
