local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 15.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  
  width: 6.0
  height: 6.0
  resolution: 0.03
  transform_tolerance: 0.5
  
  plugins:
    - {name: obstacles,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,  type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {
      sensor_frame: lidar_link, 
      data_type: LaserScan, 
      topic: /scan, 
      marking: true, 
      clearing: true, 
      min_obstacle_height: 0.05, 
      max_obstacle_height: 1.0,
      obstacle_range: 7.0,
      raytrace_range: 7.5,
      inf_is_valid: false,
      obstacle_detection_threshold: 0.7
    }
    





# local_costmap:
#   global_frame: odom
#   robot_base_frame: base_link
#   update_frequency: 3.0
#   publish_frequency: 1.0
#   static_map: false
#   rolling_window: true
#   width: 6.0
#   height: 6.0
#   resolution: 0.05
#   transform_tolerance: 0.5