controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    # Joint State Broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController

effort_controller:
  ros__parameters:
    joints:
      - left_rocker_arm_joint
      - right_rocker_arm_joint
    
    command_interfaces:
      - effort

    state_intefaces:
      - position  


    # Rocker Arm Position Controller
#     rocker_arm_position_controller:
#       type: position_controllers/JointGroupPositionController

# rocker_arm_position_controller:
#   ros__parameters:
#     joints:
#       - left_rocker_arm_joint
#       - right_rocker_arm_joint
#     pid:
#       p: 10.0
#       i: 0.1
#       d: 0.01