controller_manager:
  ros__parameters:
    update_rate: 100

    left_front_wheel_controller:
      type: "effort_controllers/JointEffortController"
      joint: "left_front_wheel_joint"
      pid:
        p: 100.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0

    left_rear_wheel_controller:
      type: "effort_controllers/JointEffortController"
      joint: "left_rear_wheel_joint"
      pid:
        p: 100.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0

    right_front_wheel_controller:
      type: "effort_controllers/JointEffortController"
      joint: "right_front_wheel_joint"
      pid:
        p: 100.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0

    right_rear_wheel_controller:
      type: "effort_controllers/JointEffortController"
      joint: "right_rear_wheel_joint"
      pid:
        p: 100.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0

    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    left_rocker_position_controller:
      type: effort_controllers/JointPositionController
      joint: left_rocker_arm_joint
      pid:
        p: 8.0
        i: 5.0
        d: 5.0

    right_rocker_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_rocker_arm_joint
      pid:
        p: 8.0
        i: 5.0
        d: 5.0